// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AAvatar: typeof import("ant-design-vue/es")["Avatar"];
    AInput: typeof import("ant-design-vue/es")["Input"];
    HelloWorld: typeof import("./src/components/HelloWorld.vue")["default"];
    MenuFoldOutlined: typeof import("@ant-design/icons-vue")["MenuFoldOutlined"];
    MenuUnfoldOutlined: typeof import("@ant-design/icons-vue")["MenuUnfoldOutlined"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    UserOutlined: typeof import("@ant-design/icons-vue")["UserOutlined"];
  }
}
